version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data  # папка для БД на хосте
    environment:
      - DATABASE_PATH=./data/app.db  # путь к БД внутри контейнера
      - SECRET_KEY=${SECRET_KEY}
    restart: always