"""add notification fields

Revision ID: 00ec8da4b159
Revises: 5bfb14a52ebb
Create Date: 2026-07-08 22:43:53.155149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00ec8da4b159'
down_revision: Union[str, Sequence[str], None] = '5bfb14a52ebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replacements', sa.Column('critical_notified', sa.Boolean(), nullable=True))
    op.add_column('replacements', sa.Column('overdue_notified_at_km', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('oil_notify_enabled', sa.Boolean(), nullable=True))
    op.add_column('vehicles', sa.Column('transmission_notify_enabled', sa.Boolean(), nullable=True))
    op.add_column('vehicles', sa.Column('brake_notify_enabled', sa.Boolean(), nullable=True))
    op.add_column('vehicles', sa.Column('coolant_notify_enabled', sa.Boolean(), nullable=True))
    op.add_column('vehicles', sa.Column('power_steering_notify_enabled', sa.Boolean(), nullable=True))
    op.add_column('vehicles', sa.Column('differential_oil_notify_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'differential_oil_notify_enabled')
    op.drop_column('vehicles', 'power_steering_notify_enabled')
    op.drop_column('vehicles', 'coolant_notify_enabled')
    op.drop_column('vehicles', 'brake_notify_enabled')
    op.drop_column('vehicles', 'transmission_notify_enabled')
    op.drop_column('vehicles', 'oil_notify_enabled')
    op.drop_column('replacements', 'overdue_notified_at_km')
    op.drop_column('replacements', 'critical_notified')
    # ### end Alembic commands ###
